package pe.egcc.eurekaapp.view;

import javax.swing.JInternalFrame;
import pe.egcc.eurekaapp.model.Empleado;
import pe.egcc.eurekaapp.util.Session;

/**
 *
 * @author Gustavo Coronel Castillo
 * @blog gcoronelc.blogspot.com
 * @email gcoronelc@gmail.com
 */
public class MainView extends javax.swing.JFrame {

  public MainView() {
    initComponents();
    establecerTitulo();
    this.setExtendedState(MAXIMIZED_BOTH);
  }

  private void establecerTitulo() {
    Empleado bean;
    bean = (Empleado) Session.get("usuario");
    String titulo = "EUREKA APP";
    titulo += " [Usuario:" + bean.getUsuario() + "]";
    this.setTitle(titulo);
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    desktopPane = new javax.swing.JDesktopPane();
    jToolBar1 = new javax.swing.JToolBar();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    jButton3 = new javax.swing.JButton();
    jButton4 = new javax.swing.JButton();
    jButton5 = new javax.swing.JButton();
    jSeparator1 = new javax.swing.JToolBar.Separator();
    btnClientes = new javax.swing.JButton();
    btnEmpleados = new javax.swing.JButton();
    btnSucursales = new javax.swing.JButton();
    jSeparator2 = new javax.swing.JToolBar.Separator();
    btnSalir = new javax.swing.JButton();
    menuBar = new javax.swing.JMenuBar();
    menuArchivo = new javax.swing.JMenu();
    menuArchivoSalir = new javax.swing.JMenuItem();
    menuProcesos = new javax.swing.JMenu();
    menuProcesosRetiro = new javax.swing.JMenuItem();
    menuTablas = new javax.swing.JMenu();
    menuTablasClientes = new javax.swing.JMenuItem();
    menuTablasEmpleados = new javax.swing.JMenuItem();
    menuTablasSucursales = new javax.swing.JMenuItem();
    menuConsultas = new javax.swing.JMenu();
    menuConsultaResumen001 = new javax.swing.JMenuItem();
    menuReportes = new javax.swing.JMenu();
    menuUtil = new javax.swing.JMenu();
    menuAyuda = new javax.swing.JMenu();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jToolBar1.setFloatable(false);
    jToolBar1.setRollover(true);

    jButton1.setText("jButton1");
    jButton1.setFocusable(false);
    jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jToolBar1.add(jButton1);

    jButton2.setText("jButton2");
    jButton2.setFocusable(false);
    jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jToolBar1.add(jButton2);

    jButton3.setText("jButton3");
    jButton3.setFocusable(false);
    jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jToolBar1.add(jButton3);

    jButton4.setText("jButton4");
    jButton4.setFocusable(false);
    jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jToolBar1.add(jButton4);

    jButton5.setText("jButton5");
    jButton5.setFocusable(false);
    jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jToolBar1.add(jButton5);
    jToolBar1.add(jSeparator1);

    btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/egcc/eurekaapp/img/cliente.png"))); // NOI18N
    btnClientes.setToolTipText("Clientes");
    btnClientes.setFocusable(false);
    btnClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    btnClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jToolBar1.add(btnClientes);

    btnEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/egcc/eurekaapp/img/empleado.png"))); // NOI18N
    btnEmpleados.setToolTipText("Empleados");
    btnEmpleados.setFocusable(false);
    btnEmpleados.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    btnEmpleados.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jToolBar1.add(btnEmpleados);

    btnSucursales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/egcc/eurekaapp/img/sucursal.png"))); // NOI18N
    btnSucursales.setToolTipText("Sucursales");
    btnSucursales.setFocusable(false);
    btnSucursales.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    btnSucursales.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jToolBar1.add(btnSucursales);
    jToolBar1.add(jSeparator2);

    btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/egcc/eurekaapp/img/salir.png"))); // NOI18N
    btnSalir.setToolTipText("Salir");
    btnSalir.setFocusable(false);
    btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    btnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    btnSalir.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSalirActionPerformed(evt);
      }
    });
    jToolBar1.add(btnSalir);

    menuArchivo.setText("Archivo");

    menuArchivoSalir.setText("Salir");
    menuArchivoSalir.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        menuArchivoSalirActionPerformed(evt);
      }
    });
    menuArchivo.add(menuArchivoSalir);

    menuBar.add(menuArchivo);

    menuProcesos.setText("Procesos");

    menuProcesosRetiro.setText("Retiro");
    menuProcesosRetiro.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        menuProcesosRetiroActionPerformed(evt);
      }
    });
    menuProcesos.add(menuProcesosRetiro);

    menuBar.add(menuProcesos);

    menuTablas.setText("Tablas");

    menuTablasClientes.setText("Clientes");
    menuTablas.add(menuTablasClientes);

    menuTablasEmpleados.setText("Empleados");
    menuTablas.add(menuTablasEmpleados);

    menuTablasSucursales.setText("Sucursales");
    menuTablas.add(menuTablasSucursales);

    menuBar.add(menuTablas);

    menuConsultas.setText("Consultas");

    menuConsultaResumen001.setText("Resumen 001");
    menuConsultaResumen001.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        menuConsultaResumen001ActionPerformed(evt);
      }
    });
    menuConsultas.add(menuConsultaResumen001);

    menuBar.add(menuConsultas);

    menuReportes.setText("Reportes");
    menuBar.add(menuReportes);

    menuUtil.setText("Utilitarios");
    menuBar.add(menuUtil);

    menuAyuda.setText("Ayuda");
    menuBar.add(menuAyuda);

    setJMenuBar(menuBar);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
      .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, 0)
        .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
        .addGap(0, 0, 0))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void menuArchivoSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuArchivoSalirActionPerformed
    System.exit(0);
  }//GEN-LAST:event_menuArchivoSalirActionPerformed

  private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
    System.exit(0);
  }//GEN-LAST:event_btnSalirActionPerformed

  private void menuConsultaResumen001ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultaResumen001ActionPerformed
    cargarFormulario(Resumen001View.class);
  }//GEN-LAST:event_menuConsultaResumen001ActionPerformed

  private void menuProcesosRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProcesosRetiroActionPerformed
    cargarFormulario(ProcRetiroView.class);
  }//GEN-LAST:event_menuProcesosRetiroActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new MainView().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnClientes;
  private javax.swing.JButton btnEmpleados;
  private javax.swing.JButton btnSalir;
  private javax.swing.JButton btnSucursales;
  private javax.swing.JDesktopPane desktopPane;
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JButton jButton3;
  private javax.swing.JButton jButton4;
  private javax.swing.JButton jButton5;
  private javax.swing.JToolBar.Separator jSeparator1;
  private javax.swing.JToolBar.Separator jSeparator2;
  private javax.swing.JToolBar jToolBar1;
  private javax.swing.JMenu menuArchivo;
  private javax.swing.JMenuItem menuArchivoSalir;
  private javax.swing.JMenu menuAyuda;
  private javax.swing.JMenuBar menuBar;
  private javax.swing.JMenuItem menuConsultaResumen001;
  private javax.swing.JMenu menuConsultas;
  private javax.swing.JMenu menuProcesos;
  private javax.swing.JMenuItem menuProcesosRetiro;
  private javax.swing.JMenu menuReportes;
  private javax.swing.JMenu menuTablas;
  private javax.swing.JMenuItem menuTablasClientes;
  private javax.swing.JMenuItem menuTablasEmpleados;
  private javax.swing.JMenuItem menuTablasSucursales;
  private javax.swing.JMenu menuUtil;
  // End of variables declaration//GEN-END:variables

  private void cargarFormulario(Class<?> aClass) {
    try {
      // Variable de control
      JInternalFrame view = null;
      // Buscar instancia
      for (JInternalFrame f : desktopPane.getAllFrames()) {
        if (aClass.isInstance(f)) {
          view = f;
          break;
        }
      }
      // Crear la instancia
      if (view == null) {
        view = (JInternalFrame) Class.forName(aClass.getName()).newInstance();
        desktopPane.add(view);
        view.setVisible(true);
      }
      // Activar el formulario
      view.setMaximum(true);
      view.setSelected(true);
    } catch (Exception e) {
    }
  }
}
